import { NextResponse } from "next/server";

const packageList = [
  {
    id: 1,
    title: "Amazing Thailand Tour",
    location: "Thailand, Bangkok",
    duration: "5N - 4D",
    meals: "View",
    mealsAction: "View",
    flights: "View",
    flightsAction: "View",
    hotel: "View",
    hotelAction: "View",
    transport: "View",
    transportAction: "View",
    vendorName: "Thai Tours Ltd",
    price: "$999",
    status: "Active",
  },
  {
    id: 2,
    title: "Dubai Adventure",
    location: "UAE, Dubai",
    duration: "4N - 3D",
    meals: "NA",
    mealsAction: "NA",
    flights: "View",
    flightsAction: "View",
    hotel: "View",
    hotelAction: "View",
    transport: "NA",
    transportAction: "NA",
    vendorName: "Dubai Travels",
    price: "$1499",
    status: "Pending",
  },
  {
    id: 3,
    title: "Bali Paradise Package",
    location: "Indonesia, Bali",
    duration: "7N - 6D",
    meals: "View",
    mealsAction: "View",
    flights: "View",
    flightsAction: "View",
    hotel: "View",
    hotelAction: "View",
    transport: "View",
    transportAction: "View",
    vendorName: "Bali Expeditions",
    price: "$1299",
    status: "Active",
  },
  {
    id: 4,
    title: "Tokyo City Explorer",
    location: "Japan, Tokyo",
    duration: "6N - 5D",
    meals: "View",
    mealsAction: "View",
    flights: "NA",
    flightsAction: "NA",
    hotel: "View",
    hotelAction: "View",
    transport: "View",
    transportAction: "View",
    vendorName: "Japan Tours Co.",
    price: "$2199",
    status: "Active",
  },
  {
    id: 5,
    title: "Singapore Family Holiday",
    location: "Singapore",
    duration: "4N - 3D",
    meals: "View",
    mealsAction: "View",
    flights: "View",
    flightsAction: "View",
    hotel: "View",
    hotelAction: "View",
    transport: "View",
    transportAction: "View",
    vendorName: "SG Holidays",
    price: "$1399",
    status: "Cancelled",
  },
  {
    id: 6,
    title: "Maldives Beach Retreat",
    location: "Maldives, Male",
    duration: "5N - 4D",
    meals: "View",
    mealsAction: "View",
    flights: "View",
    flightsAction: "View",
    hotel: "View",
    hotelAction: "View",
    transport: "NA",
    transportAction: "NA",
    vendorName: "Maldives Escapes",
    price: "$2499",
    status: "Active",
  },
  {
    id: 7,
    title: "Seoul K-Culture Tour",
    location: "South Korea, Seoul",
    duration: "6N - 5D",
    meals: "NA",
    mealsAction: "NA",
    flights: "View",
    flightsAction: "View",
    hotel: "View",
    hotelAction: "View",
    transport: "View",
    transportAction: "View",
    vendorName: "Korea Travel Pro",
    price: "$1699",
    status: "Pending",
  },
  {
    id: 8,
    title: "Vietnam Heritage Tour",
    location: "Vietnam, Hanoi",
    duration: "8N - 7D",
    meals: "View",
    mealsAction: "View",
    flights: "View",
    flightsAction: "View",
    hotel: "View",
    hotelAction: "View",
    transport: "View",
    transportAction: "View",
    vendorName: "Vietnam Ventures",
    price: "$1199",
    status: "Active",
  },
  {
    id: 9,
    title: "Malaysia City & Nature",
    location: "Malaysia, Kuala Lumpur",
    duration: "5N - 4D",
    meals: "View",
    mealsAction: "View",
    flights: "NA",
    flightsAction: "NA",
    hotel: "View",
    hotelAction: "View",
    transport: "View",
    transportAction: "View",
    vendorName: "MY Tours",
    price: "$999",
    status: "Cancelled",
  },
  {
    id: 10,
    title: "Hong Kong Discovery",
    location: "Hong Kong",
    duration: "4N - 3D",
    meals: "View",
    mealsAction: "View",
    flights: "View",
    flightsAction: "View",
    hotel: "View",
    hotelAction: "View",
    transport: "View",
    transportAction: "View",
    vendorName: "HK Explorers",
    price: "$1599",
    status: "Active",
  },
  {
    id: 11,
    title: "Beijing Cultural Tour",
    location: "China, Beijing",
    duration: "7N - 6D",
    meals: "View",
    mealsAction: "View",
    flights: "View",
    flightsAction: "View",
    hotel: "View",
    hotelAction: "View",
    transport: "View",
    transportAction: "View",
    vendorName: "China Tours Plus",
    price: "$1799",
    status: "Pending",
  },
  {
    id: 12,
    title: "Philippines Island Hopping",
    location: "Philippines, Cebu",
    duration: "6N - 5D",
    meals: "View",
    mealsAction: "View",
    flights: "View",
    flightsAction: "View",
    hotel: "View",
    hotelAction: "View",
    transport: "NA",
    transportAction: "NA",
    vendorName: "Philippine Adventures",
    price: "$1299",
    status: "Active",
  },
];

// GET handler to fetch flight bookings with pagination
export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const page = parseInt(searchParams.get("page") || "1", 10);
  const limit = parseInt(searchParams.get("limit") || "2", 10);

  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;

  const paginatedData = packageList.slice(startIndex, endIndex);

  const totalPages = Math.ceil(packageList.length / limit);

  return NextResponse.json({
    page,
    limit,
    totalPages,
    totalItems: packageList.length,
    data: paginatedData,
  });
}
